service: nestjs-serverless

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    REDIS_URL: ${env:REDIS_URL}
    AWS_REGION: us-east-1
    AWS_S3_BUCKET: your-bucket
    SQS_URL: ${env:SQS_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: 'arn:aws:s3:::your-bucket/*'

        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: '*'
functions:
  api:
    handler: dist/src/lambda/lambda.handler
    timeout: 30
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
