service: nestjs-serverless

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1

functions:
  api:
    handler: dist/src/lambda/lambda.handler
    timeout: 30
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
